site/src/Entity/TimestampTrait.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

trait TimestampTrait
{
    /**
     * @ORM\Column(type="datetime", nullable=true, options={"comment":"Дата создания"})
     */
    private ?DateTimeInterface $created_at = null;

    /**
     * @ORM\Column(type="datetime", nullable=true, options={"comment":"Дата изменения"})
     */
    private ?DateTimeInterface $updated_at = null;

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @param DateTimeInterface|null $created_at
     * @return $this
     */
    public function setCreatedAt(?DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @param DateTimeInterface|null $updated_at
     * @return $this
     */
    public function setUpdatedAt(?DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

site/src/Controller/Admin/Agency/CabinetController.php
<?php

namespace App\Controller\Admin\Agency;

use App\Agency\MyTargetApi;
use App\Entity\Main\Agency\AgencyCabinet;
use App\Entity\Main\User;
use App\Form\AgencyCabinetType;
use App\Form\Cabinet\Agency\FromFileAgencyCabinetType;
use App\Repository\Main\Agency\AgencyCabinetRepository;
use App\Repository\Main\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Psr\Cache\InvalidArgumentException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\DecodingExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;

/**
 * @Route("/admin/agency/cabinet", name="admin_agency_cabinet_")
 */
class CabinetController extends AbstractController
{
    /**
     * @Route("/{page}", name="index", requirements={"page"="\d+"}, methods={"GET"})
     * @param AgencyCabinetRepository $agencyCabinetRepository
     * @param UserRepository $userRepository
     * @param PaginatorInterface $paginator
     * @param int $page
     * @return Response
     */
    public function index(AgencyCabinetRepository $agencyCabinetRepository, UserRepository $userRepository, PaginatorInterface $paginator, int $page = 1)
    {
        $query = $agencyCabinetRepository
            ->createQueryBuilder('ac')
            ->addSelect(['ac', 'u'])
            ->leftJoin('ac.user', 'u')
            ->orderBy('ac.name')
            ->orderBy('ac.id', 'DESC')
            ->getQuery();
        $pagination = $paginator->paginate($query, $page, 100);

        $users = $userRepository->findAll();

        return $this->render('admin/agency/cabinet/index.html.twig', [
            'pagination' => $pagination,
            'users' => $users,
        ]);
    }

    /**
     * @Route("/cabinet-to-user", name="cabinet_to_user")
     * @param Request $request
     * @param AgencyCabinetRepository $agencyCabinetRepository
     * @param UserRepository $userRepository
     * @return RedirectResponse
     */
    public function cabinetToUser(Request $request, AgencyCabinetRepository $agencyCabinetRepository, UserRepository $userRepository)
    {
        $agencyCabinet = $agencyCabinetRepository->find($request->request->get('id'));
        $toUser = $userRepository->find($request->request->get('user_id'));

        if (is_null($agencyCabinet) !== null && is_null($toUser) !== null) {
            $agencyCabinet->setUser($toUser);
            $this->getDoctrine()->getManager()->persist($agencyCabinet);
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->redirectToRoute('admin_agency_cabinet_index');
    }


    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     * @param MyTargetApi $myTargetApi
     * @param SerializerInterface $serializer
     * @param UserRepository $userRepository
     * @param Request $request
     * @return Response
     * @throws ClientExceptionInterface
     * @throws DecodingExceptionInterface
     * @throws InvalidArgumentException
     * @throws RedirectionExceptionInterface
     * @throws ServerExceptionInterface
     * @throws TransportExceptionInterface
     */
    public function new(MyTargetApi $myTargetApi, SerializerInterface $serializer, UserRepository $userRepository, Request $request)
    {
        /** @var User $user */
        $user = $userRepository->findOneBy(['email' => User::SYSTEM_USER_MYTARGET]);
        $agencyCabinet = new AgencyCabinet();

        $form = $this->createForm(AgencyCabinetType::class, $agencyCabinet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $apiClient = $myTargetApi->getClientByUsername($agencyCabinet->getApiName());

            if (is_null($apiClient) === false) {
                $agencyCabinet->setUser($user);
                $agencyCabinet->setApiId($apiClient->getUser()->getId());
                $agencyCabinet->setBalance($apiClient->getUser()->getAccount()->getBalance());
                $agencyCabinet->setAutoCompletion(false);
                $agencyCabinet->setBalanceBelow(0);
                $agencyCabinet->setReplenishmentAmount(0);
                $agencyCabinet->setStatus(1);
                $agencyCabinet->setType(AgencyCabinet::TYPE_MYTARGET);
                $agencyCabinet->setParams(json_decode($serializer->serialize($apiClient, 'json'), true));

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($agencyCabinet);
                $entityManager->flush();
            }

            return $this->redirectToRoute('admin_agency_cabinet_index');
        }

        return $this->render('admin/agency/cabinet/new.html.twig', [
            'agencyCabinet' => $agencyCabinet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/load-from-file", name="load_from_file", methods={"GET","POST"})
     * @param MyTargetApi $myTargetApi
     * @param UserRepository $userRepository
     * @param AgencyCabinetRepository $agencyCabinetRepository
     * @param SerializerInterface $serializer
     * @param Request $request
     * @return Response
     * @throws InvalidArgumentException
     */
    public function loadFromFile(MyTargetApi $myTargetApi, UserRepository $userRepository, AgencyCabinetRepository $agencyCabinetRepository, SerializerInterface $serializer, Request $request)
    {
        $form = $this->createForm(FromFileAgencyCabinetType::class);
        $form->handleRequest($request);

        $errors = [];
        if ($form->isSubmitted() && $form->isValid()) {

            $user = $userRepository->findOneBy(['email' => User::SYSTEM_USER_MYTARGET]);

            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('file')->getData();

            $handle = @fopen($brochureFile->getPathname(), 'r');

            $accounts = [];
            if ($handle) {
                while (($buffer = fgets($handle, 4096)) !== false) {
                    $accounts[] = explode(':', trim($buffer));
                }
                //if (!feof($handle)) {
                //    echo "Ошибка: fgets() неожиданно потерпел неудачу\n";
                //}
                fclose($handle);
            }

            $entityManager = $this->getDoctrine()->getManager();

            foreach ($accounts as $account) {
                try {
                    $apiClient = $myTargetApi->getClientByUsername($account[0]);
                    $agencyCabinet = $agencyCabinetRepository->findOneBy(['apiId' => $apiClient->getUser()->getId()]);

                    if (is_null($agencyCabinet) === false) {
                        throw new \Exception('Кабинет уже сущевствует');
                    }

                    $agencyCabinet = new AgencyCabinet();
                    $agencyCabinet->setUser($user);
                    $agencyCabinet->setApiName($apiClient->getUser()->getUsername());
                    $agencyCabinet->setName($apiClient->getUser()->getUsername());
                    $agencyCabinet->setPassword($account[1]);
                    $agencyCabinet->setApiId($apiClient->getUser()->getId());
                    $agencyCabinet->setBalance($apiClient->getUser()->getAccount()->getBalance());
                    $agencyCabinet->setAutoCompletion(false);
                    $agencyCabinet->setBalanceBelow(0);
                    $agencyCabinet->setReplenishmentAmount(0);
                    $agencyCabinet->setStatus(1);
                    $agencyCabinet->setType(AgencyCabinet::TYPE_MYTARGET);
                    $agencyCabinet->setParams(json_decode($serializer->serialize($apiClient, 'json'), true));

                    $entityManager->persist($agencyCabinet);

                } catch (\Throwable $exception) {
                    $errors[] = $account;
                }

                $entityManager->flush();
            }
        }

        return $this->render('admin/agency/cabinet/load_from_file.html.twig', [
            'form' => $form->createView(),
            'errors' => $errors,
        ]);

    }
}

site/src/Controller/Admin/StreamController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Main\Offer;
use App\Entity\Main\Stream;
use App\Form\StreamType;
use App\Repository\Main\StreamRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/stream", name="admin_stream_")
 */
class StreamController extends AbstractController
{
    /**
     * @Route("/{page}", name="index", requirements={"page"="\d+"}, methods={"GET"})
     * @param StreamRepository $streamRepository
     * @param PaginatorInterface $paginator
     * @param int $page
     * @return Response
     */
    public function index(StreamRepository $streamRepository, PaginatorInterface $paginator, int $page = 1): Response
    {
        $query = $streamRepository->createQueryBuilder('s')
            ->leftJoin('s.offer', 'o')
            ->leftJoin('s.trafficSource', 'ts')
            ->leftJoin('ts.user', 'u')
            ->addSelect(['o', 'u', 'ts'])
            ->getQuery();

        $pagination = $paginator->paginate($query, $page, 100);

        return $this->render('admin/stream/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    /**
     * @Route("/new/{offer}/{trafficSource}", name="new", methods={"GET","POST"})
     * @param Request $request
     * @param Offer|null $offer
     * @param TrafficSource|null $trafficSource
     * @return Response
     */
    public function new(Request $request, ?Offer $offer = null, ?TrafficSource $trafficSource = null): Response
    {
        $stream = new Stream();
        $stream->setOffer($offer);
        $stream->setTrafficSource($trafficSource);

        $form = $this->createForm(StreamType::class, $stream);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($stream);
            $entityManager->flush();

            return $this->redirectToRoute('admin_stream_index');
        }

        return $this->render('admin/stream/new.html.twig', [
            'stream' => $stream,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="show", methods={"GET"})
     * @param Stream $stream
     * @return Response
     */
    public function show(Stream $stream): Response
    {
        return $this->render('admin/stream/show.html.twig', [
            'stream' => $stream,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit", methods={"GET","POST"})
     * @param Request $request
     * @param Stream $stream
     * @return Response
     */
    public function edit(Request $request, Stream $stream): Response
    {
        $form = $this->createForm(StreamType::class, $stream);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_stream_index');
        }

        return $this->render('admin/stream/edit.html.twig', [
            'stream' => $stream,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete", methods={"DELETE"})
     * @param Request $request
     * @param Stream $stream
     * @return Response
     */
    public function delete(Request $request, Stream $stream): Response
    {
        if ($this->isCsrfTokenValid('delete' . $stream->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stream);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_stream_index');
    }
}

site/src/Controller/Cabinet/Agency/IndexController.php
<?php

namespace App\Controller\Cabinet\Agency;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    /**
     * @Route("/cabinet/agency", name="cabinet_agency_index")
     */
    public function index()
    {
        return $this->render('cabinet/agency/index/index.html.twig', [
            'controller_name' => 'AgencyController',
        ]);
    }

}

site/src/Controller/Cabinet/Agency/TransactionController.php
<?php

namespace App\Controller\Cabinet\Agency;

use App\Entity\Main\User;
use App\Entity\Main\UserBalance;
use App\Entity\Main\UserBalanceTransaction;
use App\Repository\Main\UserBalanceRepository;
use App\Repository\Main\UserBalanceTransactionRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/cabinet/agency/transaction", name="cabinet_agency_transaction_")
 */
class TransactionController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        return $this->render('cabinet/agency/transaction/index.html.twig', [
            'controller_name' => 'TransactionController',
        ]);
    }

    /**
     * Вывод транзакций по типу операции
     *
     * @Route("/operation/{operation}/{page?}", name="operation", requirements={"page"="\d+"}, defaults={"page"="1"})
     * @param UserBalanceRepository $userBalanceRepository
     * @param UserBalanceTransactionRepository $userBalanceTransactionRepository
     * @param PaginatorInterface $paginator
     * @param int $operation
     * @param int $page
     * @return Response
     */
    public function operation(
        UserBalanceRepository $userBalanceRepository,
        UserBalanceTransactionRepository $userBalanceTransactionRepository,
        PaginatorInterface $paginator,
        int $operation,
        int $page
    )
    {

        /** @var User $user */
        $user = $this->getUser();

        $userBalance = $userBalanceRepository->findOneBy([
            'user' => $user,
            'type' => UserBalance::TYPE_AGENCY_USD,
        ]);

        $query = $userBalanceTransactionRepository->createQueryBuilder('ubt')
            ->where('(ubt.userBalanceFrom = :userBalanceFrom OR ubt.userBalanceTo = :userBalanceTo)')
            ->andWhere('ubt.operation = :operation')
            ->andWhere('ubt.status = :status')
            ->orderBy('ubt.created_at', 'DESC')
            ->setParameter(':userBalanceFrom', $userBalance)
            ->setParameter(':userBalanceTo', $userBalance)
            ->setParameter(':operation', $operation)
            ->setParameter(':status', UserBalanceTransaction::STATUS_SUCCESS)
            ->getQuery();

        $pagination = $paginator->paginate($query, $page, 100);

        return $this->render('cabinet/agency/transaction/operation.html.twig', [
            'operation' => $operation,
            'pagination' => $pagination,
        ]);
    }
}

site/src/Controller/Cabinet/FinanceController.php
<?php

namespace App\Controller\Cabinet;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class FinanceController
 * @package App\Controller\Cabinet
 *
 * @Route("/cabinet/finance", name="cabinet_finance_")
 */
class FinanceController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        return $this->render('cabinet/finance/index.html.twig', [
            'controller_name' => 'FinanceController',
        ]);
    }
}

site/templates/cabinet/stream/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

site/templates/cabinet/stream/card.html.twig
<div class="card">
    <div class="card-header header-elements-inline">
        <h6 class="card-title">Поток: {{ stream }}</h6>
    </div>
    {#<div class="card-body">
        Контент
    </div>#}
    <div class="table-responsive">
        <table class="table table-striped table-xs">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ stream.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ stream.name }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ stream.status }}</td>
            </tr>
            <tr>
                <th>Created</th>
                <td>{{ stream.createdAt ? stream.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated</th>
                <td>{{ stream.updatedAt ? stream.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <a class="btn btn-primary btn-sm" href="{{ path('cabinet_stream_index') }}">back to list</a>
        {#<a class="btn btn-primary btn-sm" href="{{ path('admin_stream_edit', {'id': stream.id}) }}">edit</a>
        {{ include('admin/stream/_delete_form.html.twig') }}#}
    </div>
</div>

site/templates/cabinet/stream/edit.html.twig
{% extends 'cabinet/layout/base.html.twig' %}

{% block title %}редактировать поток{% endblock %}

{% block page_title %}
    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Потоки</span> - редактировать: {{ stream }}</h4>
    {#<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>#}
{% endblock %}

{% block breadcrumbs %}
    <a href="{{ path('cabinet_dashboard_index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Главная</a>
    <a class="breadcrumb-item" href="{{ path('cabinet_stream_index') }}">Потоки</a>
    <span class="breadcrumb-item active">редактировать: {{ stream }}</span>
{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">Редактировать поток: {{ stream }}</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="remove"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        {{ include('cabinet/stream/_form.html.twig') }}
    </div>
    <div class="card-footer">
        <a class="btn btn-primary btn-sm" href="{{ path('cabinet_stream_index') }}">Назад к списку</a>
    </div>
</div>
{% endblock %}

site/templates/cabinet/stream/index.html.twig
{% extends 'cabinet/layout/base.html.twig' %}

{% block title %}Потоки{% endblock %}

{% block page_title %}
    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Потоки</span>{# - 1 Sidebar#}</h4>
    {#<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>#}
{% endblock %}

{% block breadcrumbs %}
    <a href="{{ path('cabinet_dashboard_index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Главная</a>
    <span class="breadcrumb-item active">Потоки</span>
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header header-elements-inline">
            <div class="card-title">
                {{ pagination.getTotalItemCount }}
            </div>
            <div class="header-elements">
                {{ knp_pagination_filter(pagination, {
                    's.id': 'Id',
                    'o.id' : 'Оффер (id)',
                    's.name' : 'Название',
                    's.status' : 'Статус',
                    's.created_at' : 'Created',
                    's.updated_at' : 'Updated'
                }) }}
            </div>
        </div>
        {#<div class="card-body">
            Контент
        </div>#}
        <div class="table-responsive">
            <table class="table table-striped table-xs">
                <thead>
                <tr>
                    <th>{{ knp_pagination_sortable(pagination, 'Id', 's.id') }}</th>
                    <th>{{ knp_pagination_sortable(pagination, 'Оффер', 'o.id') }}</th>
                    <th>{{ knp_pagination_sortable(pagination, 'Название', 's.name') }}</th>
                    <th>{{ knp_pagination_sortable(pagination, 'Статус', 's.status') }}</th>
                    <th>{{ knp_pagination_sortable(pagination, 'Создан', 's.created_at') }}</th>
                    <th>{{ knp_pagination_sortable(pagination, 'Изменен', 's.updated_at') }}</th>
                    <th>{% trans %}Actions{% endtrans %}</th>
                </tr>
                </thead>
                <tbody>
                {% for stream in pagination %}
                    <tr>
                        <td>
                            ID: {{ stream.id }}<br>
                            <small>uuid: ({{ stream.uuid }})</small>
                        </td>
                        <td>
                            <a href="{{ path('admin_offer_show', {'id':stream.offer.id}) }}">{{ stream.offer }}</a><br>
                            <small> (id: {{ stream.offer.id }})</small>
                        </td>
                        <td>{{ stream.name }}</td>
                        <td>
                            {% if stream.status == constant('App\\Entity\\Main\\Stream::STATUS_ACTIVE') %}
                                <span class="badge bg-success-400">{{ constant('App\\Entity\\Main\\Stream::STATUSES')[stream.status] }}</span>
                            {% elseif stream.status == constant('App\\Entity\\Main\\Stream::STATUS_INACTIVE') %}
                                <span class="badge bg-danger">{{ constant('App\\Entity\\Main\\Stream::STATUSES')[stream.status] }}</span>
                            {% else %}
                                <span class="badge bg-grey-400">Неизвесный статус ({{ stream.status }})</span>
                            {% endif %}
                        </td>
                        <td>{{ stream.createdAt ? stream.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ stream.updatedAt ? stream.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <div class="list-icons">
                                <a href="#" class="list-icons-item text-primary-600" title="Статистика"><i class="icon-stats-growth"></i></a>
                                <a href="{{ path('cabinet_stream_edit', {'id': stream.id}) }}" class="list-icons-item text-primary-600" title="Редактировать"><i class="icon-pencil7"></i></a>
                                <a href="{{ path('cabinet_stream_show', {'id': stream.id}) }}" class="list-icons-item text-teal-600" title="Просмотр"><i class="icon-eye"></i></a>
                            </div>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="6">{% trans %}records not found{% endtrans %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center">
            <a class="btn btn-primary btn-sm" href="{{ path('cabinet_stream_new') }}">Добавить</a>
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
{% endblock %}

site/templates/cabinet/stream/new.html.twig
{% extends 'cabinet/layout/base.html.twig' %}

{% block title %}новый поток{% endblock %}

{% block page_title %}
    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Потоки</span> - новый</h4>
    {#<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>#}
{% endblock %}

{% block breadcrumbs %}
    <a href="{{ path('cabinet_dashboard_index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Главная</a>
    <a class="breadcrumb-item" href="{{ path('cabinet_stream_index') }}">Потоки</a>
    <span class="breadcrumb-item active">Новый поток</span>
{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">Создать новый поток</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
                <a class="list-icons-item" data-action="remove"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        {{ include('cabinet/stream/_form.html.twig') }}
    </div>
    <div class="card-footer">
        <a class="btn btn-primary btn-sm" href="{{ path('cabinet_stream_index') }}">Назад к списку</a>
    </div>
</div>
{% endblock %}

site/templates/cabinet/stream/show.html.twig
{% extends 'cabinet/layout/base.html.twig' %}

{% block title %}поток {{ stream }}{% endblock %}

{% block page_title %}
    <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Потоки</span> - {{ stream }}</h4>
    {#<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>#}
{% endblock %}

{% block breadcrumbs %}
    <a href="{{ path('cabinet_dashboard_index') }}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Главная</a>
    <a class="breadcrumb-item" href="{{ path('cabinet_stream_index') }}">Потоки</a>
    <span class="breadcrumb-item active">{{ stream }}</span>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-6">
            {{ include('cabinet/stream/card.html.twig') }}
        </div>
        {#<div class="col-lg-6">
            {{ include('admin/user/card.html.twig', {'user':stream.user}) }}
            {{ include('admin/offer/card.html.twig', {'offer':stream.offer}) }}
        </div>#}
    </div>
{% endblock %}